var allDeep = [
    ["Seaweed", "NH-Icon-seaweed.png", "600", "Large", "Stationary", "All day", "(X)", "(X)", "(X)", "(X)", "(X)", "(X)", "(X)", "-", "-", "(X)", "(X)", "(X)"],
    ["Sea grapes", "NH-Icon-seagrapes.png", "900", "Small", "Stationary", "All day", "-", "-", "-", "-", "-", "(X)", "(X)", "(X)", "(X)", "-", "-", "-"],
    ["Sea cucumber", "NH-Icon-seacucumber.png", "500", "Medium", "Slow consistent movement", "All day", "(X)", "(X)", "(X)", "(X)", "-", "-", "-", "-", "-", "-", "(X)", "(X)"],
    ["Sea pig", "NH-Icon-seapig.png", "10,000", "Small", "Quick long lunges", "4pm - 9am", "(X)", "(X)", "-", "-", "-", "-", "-", "-", "-", "-", "(X)", "(X)"],
    ["Sea star", "NH-Icon-seastar.png", "500", "Small", "Slow short lunges", "All day", "(X)", "(X)", "(X)", "(X)", "(X)", "(X)", "(X)", "(X)", "(X)", "(X)", "(X)", "(X)"],
    ["Sea urchin", "NH-Icon-seaurchin.png", "1,700", "Small", "Slow consistent movement", "All day", "-", "-", "-", "-", "(X)", "(X)", "(X)", "(X)", "(X)", "-", "-", "-"],
    ["Slate pencil urchin", "NH-Icon-slatepencilurchin.png", "2,000", "Medium", "Moderate consistent movement", "4pm - 9am", "-", "-", "-", "-", "(X)", "(X)", "(X)", "(X)", "(X)", "-", "-", "-"],
    ["Sea anemone", "NH-Icon-seaanemone.png", "500", "Large", "Stationary", "All day", "(X)", "(X)", "(X)", "(X)", "(X)", "(X)", "(X)", "(X)", "(X)", "(X)", "(X)", "(X)"],
    ["Moon jellyfish", "NH-Icon-moonjellyfish.png", "600", "Small", "Slow consistent movement", "All day", "-", "-", "-", "-", "-", "-", "(X)", "(X)", "(X)", "-", "-", "-"],
    ["Sea slug", "NH-Icon-seaslug.png", "600", "Tiny", "Slow consistent movement", "All day", "(X)", "(X)", "(X)", "(X)", "(X)", "(X)", "(X)", "(X)", "(X)", "(X)", "(X)", "(X)"],
    ["Pearl oyster", "NH-Icon-pearloyster.png", "2,800", "Small", "Moderate long lunges", "All day", "(X)", "(X)", "(X)", "(X)", "(X)", "(X)", "(X)", "(X)", "(X)", "(X)", "(X)", "(X)"],
    ["Mussel", "NH-Icon-mussel.png", "1,500", "Small", "Slow consistent movement", "All day", "-", "-", "-", "-", "-", "(X)", "(X)", "(X)", "(X)", "(X)", "(X)", "(X)"],
    ["Oyster", "NH-Icon-oyster.png", "1,100", "Small", "Moderate short lunges", "All day", "(X)", "(X)", "-", "-", "-", "-", "-", "-", "(X)", "(X)", "(X)", "(X)"],
    ["Scallop", "NH-Icon-scallop.png", "1,200", "Medium", "Slow long lunges", "All day", "(X)", "(X)", "(X)", "(X)", "(X)", "(X)", "(X)", "(X)", "(X)", "(X)", "(X)", "(X)"],
    ["Whelk", "NH-Icon-whelk.png", "1,000", "Small", "Slow consistent movement", "All day", "(X)", "(X)", "(X)", "(X)", "(X)", "(X)", "(X)", "(X)", "(X)", "(X)", "(X)", "(X)"],
    ["Turban shell", "NH-Icon-turbanshell.png", "1,000", "Small", "Slow", "All day", "-", "-", "(X)", "(X)", "(X)", "-", "-", "-", "(X)", "(X)", "(X)", "(X)"],
    ["Abalone", "NH-Icon-abalone.png", "2,000", "Medium", "Moderate consistent movement", "4pm - 9am", "(X)", "-", "-", "-", "-", "(X)", "(X)", "(X)", "(X)", "(X)", "(X)", "(X)"],
    ["Gigas giant clam", "NH-Icon-gigasgiantclam.png", "15,000", "Huge", "Quick long lunges", "All day", "-", "-", "-", "-", "(X)", "(X)", "(X)", "(X)", "(X)", "-", "-", "-"],
    ["Chambered nautilus", "NH-Icon-chamberednautilus.png", "1,800", "Medium", "Slow", "4pm - 9am", "-", "-", "(X)", "(X)", "(X)", "(X)", "-", "-", "(X)", "(X)", "(X)", "-"],
    ["Octopus", "NH-Icon-octopus.png", "1,200", "Medium", "Moderate long lunges", "All day", "(X)", "(X)", "(X)", "(X)", "(X)", "(X)", "(X)", "(X)", "(X)", "(X)", "(X)", "(X)"],
    ["Umbrella octopus", "NH-Icon-umbrellaoctopus.png", "6,000", "Small", "Quick long lunges", "All day", "-", "-", "(X)", "(X)", "(X)", "-", "-", "-", "(X)", "(X)", "(X)", "-"],
    ["Vampire squid", "NH-Icon-vampiresquid.png", "10,000", "Medium", "Quick long lunges", "5pm - 9am", "-", "-", "-", "-", "(X)", "(X)", "(X)", "(X)", "-", "-", "-", "-"],
    ["Firefly squid", "NH-Icon-fireflysquid.png", "1,400", "Tiny", "Slow", "9pm - 4am", "-", "-", "(X)", "(X)", "(X)", "(X)", "-", "-", "-", "-", "-", "-"],
    ["Gazami crab", "NH-Icon-gazamicrab.png", "2,200", "Medium", "Moderate long lunges", "All day", "-", "-", "-", "-", "-", "(X)", "(X)", "(X)", "(X)", "(X)", "(X)", "-"],
    ["Dungeness crab", "NH-Icon-dungenesscrab.png", "1,900", "Medium", "Moderate consistent movement", "All day", "(X)", "(X)", "(X)", "(X)", "(X)", "-", "-", "-", "-", "-", "(X)", "(X)"],
    ["Snow crab", "NH-Icon-snowcrab.png", "6,000", "Large", "Quick short lunges", "All day", "(X)", "(X)", "(X)", "(X)", "-", "-", "-", "-", "-", "-", "(X)", "(X)"],
    ["Red king crab", "NH-Icon-redkingcrab.png", "8,000", "Large", "Quick", "All day", "(X)", "(X)", "(X)", "-", "-", "-", "-", "-", "-", "-", "(X)", "(X)"],
    ["Acorn barnacle", "NH-Icon-acornbarnacle.png", "600", "Tiny", "Stationary", "All day", "(X)", "(X)", "(X)", "(X)", "(X)", "(X)", "(X)", "(X)", "(X)", "(X)", "(X)", "(X)"],
    ["Spider crab", "NH-Icon-spidercrab.png", "12,000", "Huge", "Quick", "All day", "-", "-", "(X)", "(X)", "-", "-", "-", "-", "-", "-", "-", "-"],
    ["Tiger prawn", "NH-Icon-tigerprawn.png", "3,000", "Small", "Moderate consistent movement", "4pm - 9am", "-", "-", "-", "-", "-", "(X)", "(X)", "(X)", "(X)", "-", "-", "-"],
    ["Sweet shrimp", "NH-Icon-sweetshrimp.png", "1,400", "Small", "Slow", "4pm - 9am", "(X)", "(X)", "-", "-", "-", "-", "-", "-", "(X)", "(X)", "(X)", "(X)"],
    ["Mantis shrimp", "NH-Icon-mantisshrimp.png", "2,500", "Small", "Quick short lunges", "4pm - 9am", "(X)", "(X)", "(X)", "(X)", "(X)", "(X)", "(X)", "(X)", "(X)", "(X)", "(X)", "(X)"],
    ["Spiny lobster", "NH-Icon-spinylobster.png", "5,000", "Large", "Fast", "9pm - 4am", "-", "-", "-", "-", "-", "-", "-", "-", "-", "(X)", "(X)", "(X)"],
    ["Lobster", "NH-Icon-lobster.png", "4,500", "Large", "Quick", "All day", "(X)", "-", "-", "(X)", "(X)", "(X)", "-", "-", "-", "-", "-", "(X)"],
    ["Giant isopod", "NH-Icon-giantisopod.png", "12,000", "Medium", "Quick long lunges", "9am - 4pm & 9pm - 4am", "-", "-", "-", "-", "-", "-", "(X)", "(X)", "(X)", "(X)", "-", "-"],
    ["Horseshoe Crab", "NH-Icon-horseshoecrab.png", "2,500", "Medium", "Quick short lunges", "9pm - 4am", "-", "-", "-", "-", "-", "-", "(X)", "(X)", "(X)", "-", "-", "-"],
    ["Sea pineapple", "NH-Icon-seapineapple.png", "1,500", "Small", "Slow long lunges", "All day", "-", "-", "-", "(X)", "(X)", "(X)", "(X)", "(X)", "-", "-", "-", "-"],
    ["Spotted garden eel", "NH-Icon-spottedgardeneel.png", "1,100", "Small", "Slow consistent movement", "4am - 9pm", "-", "-", "-", "-", "(X)", "(X)", "(X)", "(X)", "(X)", "(X)", "-", "-"],
    ["Flatworm", "NH-Icon-flatworm.png", "700", "Tiny", "Slow short movement", "4pm - 9am", "-", "-", "-", "-", "-", "-", "-", "(X)", "(X)", "-", "-", "-"],
    ["Venus' flower basket", "NH-Icon-venusflowerbasket.png", "5,000", "Medium", "Quick long lunges", "All day", "(X)", "(X)", "-", "-", "-", "-", "-", "-", "-", "(X)", "(X)", "(X)"]
];